# Generated by Django 3.0.5 on 2020-05-23 10:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=35)),
                ('userName', models.CharField(max_length=20)),
                ('emailOrPhone', models.CharField(max_length=30)),
                ('fotoUrl', models.CharField(blank=True, max_length=200, null=True)),
                ('followers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), blank=True, null=True, size=None)),
                ('following', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), blank=True, null=True, size=None)),
                ('bildirim', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), blank=True, null=True, size=None)),
                ('mesafe', models.FloatField(default=2)),
            ],
        ),
    ]
