# Generated by Django 3.0.5 on 2020-05-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0002_auto_20200523_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='fotoUrl',
            field=models.CharField(default='https://pngimage.net/wp-content/uploads/2018/06/profile-png-icon-1.png', max_length=200),
        ),
    ]
