# Generated by Django 3.0.5 on 2020-05-26 15:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0003_auto_20200524_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='checkIn',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), blank=True, null=True, size=None),
        ),
    ]
