# Generated by Django 3.0.5 on 2020-05-29 07:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaruantAd', models.CharField(blank=True, max_length=20, null=True)),
                ('checkin', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), blank=True, null=True, size=None)),
                ('longitude', models.CharField(blank=True, max_length=30, null=True)),
                ('latitude', models.CharField(blank=True, max_length=30, null=True)),
                ('alkol', models.BooleanField(default=False)),
                ('canliMuzik', models.BooleanField(default=False)),
                ('okey', models.BooleanField(default=False)),
                ('nargile', models.BooleanField(default=False)),
                ('kutuOyunlari', models.BooleanField(default=False)),
                ('acilis', models.TimeField()),
                ('kapanis', models.TimeField()),
            ],
        ),
    ]
