# Generated by Django 3.0.5 on 2020-05-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaruant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kullanici',
            new_name='Restaruant',
        ),
    ]
