# Generated by Django 3.0.5 on 2020-05-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaruant', '0002_auto_20200529_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaruant',
            name='imageUrl',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
